### ISSUE TITLE
bug in burden.R

### ISSUE THREAD

**Issue by Piccetteeno** [mhguo1/PBTest#16]
Hello,
i have the following problem running burden test between 2 counts files (case vs ctrls):

Rscript burden.R --casefile pzcounts.txt --casesize 56 --controlfile ctrlcounts.txt --controlsize 112 --outfile burden_11022021.out.txt
Error in if (case_count > args$casesize) { : argument is of length zero
Execution halted

R version is 4.0.2
PS I guess you should add R "argparse" library to requirement list.
Thank you for this tool!

**Comment by FAFUshiyan** [comment]
Hi,
I had the same problem and I would like to know how you solved it?

**Comment by Piccetteeno** [comment]
Hi,
try installing "argparse" package (or "optparse" if your R version doesn't support it but then remember to replace 'library("argparse")' with 'library("optparse")' in burden.R file).
If this doesn't solve it then try to check the counts in your casefile: all the counts for each gene must be less then casesize.

Good luck!
