### ISSUE TITLE
line 249 make_snp_file.py

### ISSUE THREAD

**Issue by ivomuskens** [mhguo1/PBTest#2]
Hi,

I was trying out your package. It seems really cool! 
This is my first time reporting an issue. Apologies if it is not the typical way. 
However, I think there is a typo on line 249 of the make_snp_file.py script. I think vcfile should be vcfline. The script worked after I changed it. 

Best,
Ivo

**Comment by mhguo1** [comment]
Thanks for catching this bug--it is fixed now. Hope that you find our software useful!

**Comment by vsubasri** [comment]
^^ This error still exists.
