### ISSUE TITLE
Bug reported

### ISSUE THREAD

**Issue by CancerGenome** [mhguo1/PBTest#3]
Hi Guo,

Thanks for your software. It's very helpful in my project. I am writing to report potential bugs in both count_control.py and count_cases.py.
1) count_case.py:
Line 154 :  if options.snpformat=="VCF":

It seems like the default option should be VCFID. I have tried this command line: "python count_case.py -s test.out.txt -o counts.txt -v test.ihh.vcf.gz" and print all the SNPID. Unexpectedly, the snpids are CHRPOSREFALT format. 
Same problem was observed in count_control.py.

2) count_case.py:
Line 177: 		outfile.write(line_s[0]+"\t"+str(counts[0])+"\t"+str(counts[1])+"\t"+str(counts[2])+'\n')

I also realized that count_case.py gave you only four columns, rather than five.

**Comment by mhguo1** [comment]
Hi, glad you found our work helpful and thanks for catching these bugs! Both of them should be fixed now. Please let me know if you have any additional issues or suggestions.

**Comment by mhguo1** [comment]
Hi Wang,
I'm glad you found our work helpful and thanks for catching these bugs! Both of them should be fixed now. Please let me know if you have any additional issues or suggestions.

Best,
Mike
