### ISSUE TITLE
QQ plot bug

### ISSUE THREAD

**Issue by quentin67100** [mhguo1/PBTest#5]
When i want to use the QQ.R there are an error : 

Rscript /Users/quentinchartreux/Downloads/TRAPD-master-2/code/QQ.R --pvalfile /Users/quentinchartreux/Documents/StageM2/burden.txt --plotfile out.png 
Error in file(file, "rt") : impossible d'ouvrir la connexion
Calls: read.delim -> read.table -> file
De plus : Warning message:
In file(file, "rt") :
  impossible d'ouvrir le fichier 'burden.txt' : No such file or directory

can you help me please ?

**Comment by mhguo1** [comment]
Hi, apologies for the delayed response. Does your file "/Users/quentinchartreux/Documents/StageM2/burden.txt" exist? It seems that the issue is that R can't find that file path to read.

**Comment by quentin67100** [comment]
Hi,

Yes this file exist i copied the path directly from the file, and I also test to work directly on my macbook or on a server and I have the same issue

De : mhguo1 <notifications@github.com>
Répondre à : mhguo1/TRAPD <reply@reply.github.com>
Date : mardi 11 juin 2019 à 19:08
À : mhguo1/TRAPD <TRAPD@noreply.github.com>
Cc : Quentin CHARTREUX <chartreq@igbmc.fr>, Author <author@noreply.github.com>
Objet : Re: [mhguo1/TRAPD] QQ plot bug (#5)


Hi, apologies for the delayed response. Does your file "/Users/quentinchartreux/Documents/StageM2/burden.txt" exist? It seems that the issue is that R can't find that file path to read.

**Comment by mhguo1** [comment]
Hi Quentin, I have found the bug and fixed it. Thank you for noting this!
